@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "conversationId": "",
      "receiverId": "68e661c8398cd84364a6ebfd",
      "receiverUsername": "Janny",
      "receiverAvatarColor": "blue",
      "receiverProfilePicture": "https://res.cloudinary.com/dmxotyyvb/image/upload/v1759928759/68e661b6398cd84364a6ebf6",
      "body": "wat up bro janny",
      "gifUrl": "",
      "isRead": false,
      "selectedImage": ""
}