@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "conversationId": "68ea9d05c7646b9e5d302928",
      "receiverId": "68e661e2398cd84364a6ec05",
      "receiverUsername": "Tanny",
      "receiverAvatarColor": "blue",
      "receiverProfilePicture": "https://res.cloudinary.com/dmxotyyvb/image/upload/v1759928759/68e661b6398cd84364a6ebf6",
      "body": "we see you ",
      "gifUrl": "",
      "isRead": false,
      "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userOne": "68e66197398cd84364a6ebed",
      "userTwo": "68e661b6398cd84364a6ebf6"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userOne": "68e66197398cd84364a6ebed",
      "userTwo": "68e661b6398cd84364a6ebf6"
}

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/68e661e2398cd84364a6ec05
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/68ea9d05c7646b9e5d302927/68e66197398cd84364a6ebed/68e661e2398cd84364a6ec05/deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true

