@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo": "68e661b6398cd84364a6ebf6",
    "postId": "68e79c886a3cae38e6d1dc72",
    "comment": "this is the 2st comment",
    "profilePicture": "https://res.cloudinary.com/dmxotyyvb/image/upload/v1759061722/68d926d9c24582ef89f6998a"
}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/68e4098b276d6cf35ee12f59
Content-Type: application/json
Accept: application/json
withCredentials: true



###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/68e4098b276d6cf35ee12f59/68e51358432e606314c167fb
Content-Type: application/json
Accept: application/json
withCredentials: true

