@baseUrl = http://localhost:5000
@urlPath = api/v1

###
DELETE {{baseUrl}}/{{urlPath}}/notification/68e7ab08183972c34fd2087c
Content-Type: application/json
Accept: application/json
withCredentials: true