@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "68e24bd9f9de6c8700e01651",
  "postId": "68e2955aa66895b62fb8fc96",
  "type": "love",
  "previousReaction": "like",
  "postReactions": {
    "like": 0,
    "love": 1,
    "happy": 0,
    "sad": 0,
    "wow": 0,
    "angry": 0
  },
  "profilePicture": "https://res.cloudinary.com/dmxotyyvb/image/upload/v1759061722/68d926d9c24582ef89f6998a"
}